#!/usr/bin/env node
/**
 * Reads design-tokens/tokens.json and emits per-platform outputs.
 *  - website/src/styles/tokens.css
 *  - extension/public/styles/tokens.css
 *  - ios/CelariWallet/CelariWallet/Resources/Generated/Tokens.swift          (later task)
 *  - ios/CelariWallet/CelariWallet/Assets.xcassets/Colors/*.colorset/        (later task)
 *  - branding/exports/tokens-preview.html                                    (later task)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(import.meta.url), "../..");
const TOKENS = JSON.parse(readFileSync(resolve(ROOT, "design-tokens/tokens.json"), "utf8"));

function* walk(obj, path = []) {
  for (const [k, v] of Object.entries(obj)) {
    if (v && typeof v === "object" && !("$value" in v) && !("$dark" in v) && !("$light" in v)) {
      yield* walk(v, [...path, k]);
    } else {
      yield { path: [...path, k], leaf: v };
    }
  }
}
const kebab = (parts) => parts.join("-").replace(/_/g, "-");
const write = (p, content) => {
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
};

function buildCss() {
  const darkLines = [];
  const lightLines = [];
  const themeAgnostic = [];

  for (const group of Object.keys(TOKENS)) {
    if (group.startsWith("$")) continue;
    for (const { path, leaf } of walk(TOKENS[group])) {
      const name = `--${group}-${kebab(path)}`;
      if ("$dark" in leaf) {
        darkLines.push(`  ${name}: ${leaf.$dark};`);
        lightLines.push(`  ${name}: ${leaf.$light};`);
      } else if ("$value" in leaf) {
        themeAgnostic.push(`  ${name}: ${leaf.$value};`);
      }
    }
  }

  return [
    "/* Generated by design-tokens/build.mjs. Do not edit directly. */",
    ":root {",
    ...themeAgnostic,
    ...darkLines,
    "}",
    "",
    '[data-theme="light"] {',
    ...lightLines,
    "}",
    "",
  ].join("\n");
}

const css = buildCss();
write(resolve(ROOT, "website/src/styles/tokens.css"), css);
write(resolve(ROOT, "extension/public/styles/tokens.css"), css);

console.log("tokens: wrote CSS outputs");

function hexToRGB(hex) {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  return { r: +r.toFixed(3), g: +g.toFixed(3), b: +b.toFixed(3) };
}
function camel(parts) {
  return parts
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join("")
    .replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase());
}

function buildSwift() {
  const colorLines = [];
  for (const { path, leaf } of walk(TOKENS.color)) {
    const name = camel(["celari", ...path]);
    if ("$value" in leaf) {
      const { r, g, b } = hexToRGB(leaf.$value);
      colorLines.push(`  static let ${name} = Color(red: ${r}, green: ${g}, blue: ${b})`);
    } else if ("$dark" in leaf) {
      const d = hexToRGB(leaf.$dark);
      const l = hexToRGB(leaf.$light);
      colorLines.push(
        `  static let ${name} = Color(uiColor: UIColor { trait in`,
        `    trait.userInterfaceStyle == .dark`,
        `      ? UIColor(red: ${d.r}, green: ${d.g}, blue: ${d.b}, alpha: 1)`,
        `      : UIColor(red: ${l.r}, green: ${l.g}, blue: ${l.b}, alpha: 1)`,
        `  })`,
      );
    }
  }

  const radiusLines = Object.entries(TOKENS.radius).map(
    ([k, v]) => `  static let ${k}: CGFloat = ${parseFloat(v.$value)}`,
  );
  const motionLines = Object.entries(TOKENS.motion.duration).map(
    ([k, v]) => `  static let ${k}: Double = ${parseFloat(v.$value) / 1000}`,
  );

  return [
    "// Generated by design-tokens/build.mjs. Do not edit directly.",
    "import SwiftUI",
    "import UIKit",
    "",
    "extension Color {",
    ...colorLines,
    "}",
    "",
    "enum CelariRadius {",
    ...radiusLines,
    "}",
    "",
    "enum CelariMotion {",
    ...motionLines,
    "}",
    "",
  ].join("\n");
}

write(resolve(ROOT, "ios/CelariWallet/CelariWallet/Resources/Generated/Tokens.swift"), buildSwift());
console.log("tokens: wrote Swift output");

function xcassetsColor(rgb) {
  return {
    "color-space": "srgb",
    components: {
      red:   rgb.r.toFixed(3),
      green: rgb.g.toFixed(3),
      blue:  rgb.b.toFixed(3),
      alpha: "1.000",
    },
  };
}
function pascal(parts) {
  return parts
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("")
    .replace(/[-_]([a-zA-Z])/g, (_, c) => c.toUpperCase());
}

function writeColorset(dir, tokenPath, leaf) {
  const name = pascal(tokenPath);
  const entryDir = resolve(dir, `${name}.colorset`);
  let colors;
  if ("$value" in leaf) {
    colors = [{ idiom: "universal", color: xcassetsColor(hexToRGB(leaf.$value)) }];
  } else {
    colors = [
      { idiom: "universal", color: xcassetsColor(hexToRGB(leaf.$light)) },
      {
        idiom: "universal",
        appearances: [{ appearance: "luminosity", value: "dark" }],
        color: xcassetsColor(hexToRGB(leaf.$dark)),
      },
    ];
  }
  write(
    resolve(entryDir, "Contents.json"),
    JSON.stringify({ colors, info: { author: "xcode", version: 1 } }, null, 2),
  );
}

const xcassetsColorsDir = resolve(
  ROOT,
  "ios/CelariWallet/CelariWallet/Assets.xcassets/Colors",
);

write(
  resolve(xcassetsColorsDir, "Contents.json"),
  JSON.stringify(
    { info: { author: "xcode", version: 1 }, properties: { "provides-namespace": true } },
    null,
    2,
  ),
);

for (const { path, leaf } of walk(TOKENS.color)) {
  writeColorset(xcassetsColorsDir, path, leaf);
}

console.log("tokens: wrote xcassets output");
