#!/usr/bin/env node
/**
 * Reads design-tokens/tokens.json and emits per-platform outputs.
 *  - website/src/styles/tokens.css
 *  - extension/public/styles/tokens.css
 *  - ios/CelariWallet/CelariWallet/Resources/Generated/Tokens.swift          (later task)
 *  - ios/CelariWallet/CelariWallet/Assets.xcassets/Colors/*.colorset/        (later task)
 *  - branding/exports/tokens-preview.html                                    (later task)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(import.meta.url), "../..");
const TOKENS = JSON.parse(readFileSync(resolve(ROOT, "design-tokens/tokens.json"), "utf8"));

function* walk(obj, path = []) {
  for (const [k, v] of Object.entries(obj)) {
    if (v && typeof v === "object" && !("$value" in v) && !("$dark" in v) && !("$light" in v)) {
      yield* walk(v, [...path, k]);
    } else {
      yield { path: [...path, k], leaf: v };
    }
  }
}
const kebab = (parts) => parts.join("-").replace(/_/g, "-");
const write = (p, content) => {
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
};

function buildCss() {
  const darkLines = [];
  const lightLines = [];
  const themeAgnostic = [];

  for (const group of Object.keys(TOKENS)) {
    if (group.startsWith("$")) continue;
    for (const { path, leaf } of walk(TOKENS[group])) {
      const name = `--${group}-${kebab(path)}`;
      if ("$dark" in leaf) {
        darkLines.push(`  ${name}: ${leaf.$dark};`);
        lightLines.push(`  ${name}: ${leaf.$light};`);
      } else if ("$value" in leaf) {
        themeAgnostic.push(`  ${name}: ${leaf.$value};`);
      }
    }
  }

  return [
    "/* Generated by design-tokens/build.mjs. Do not edit directly. */",
    ":root {",
    ...themeAgnostic,
    ...darkLines,
    "}",
    "",
    '[data-theme="light"] {',
    ...lightLines,
    "}",
    "",
  ].join("\n");
}

const css = buildCss();
write(resolve(ROOT, "website/src/styles/tokens.css"), css);
write(resolve(ROOT, "extension/public/styles/tokens.css"), css);

console.log("tokens: wrote CSS outputs");
