// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
struct __private__OptionU32 __swift_bridge__$setup_srs_swift(uint32_t circuit_size, struct RustStr srs_path);
struct __private__OptionU32 __swift_bridge__$setup_srs_from_bytecode_swift(void* circuit_bytecode, struct RustStr srs_path);
struct __private__OptionU32 __swift_bridge__$setup_grumpkin_srs_swift(uint32_t num_points, struct RustStr srs_path);
void* __swift_bridge__$setup_srs_raw_swift(void* g1_data, uint32_t num_points);
void* __swift_bridge__$setup_grumpkin_srs_raw_swift(void* g1_data, uint32_t num_points);
void* __swift_bridge__$prove_swift(void* circuit_bytecode, void* initial_witness, void* proof_type, void* vkey, bool low_memory_mode, uint64_t storage_cap);
struct __private__OptionBool __swift_bridge__$verify_swift(void* proof, void* vkey, void* proof_type);
void* __swift_bridge__$execute_swift(void* circuit_bytecode, void* initial_witness);
void* __swift_bridge__$get_vkey_swift(void* circuit_bytecode, void* proof_type, bool low_memory_mode, uint64_t storage_cap);
struct __private__OptionBool __swift_bridge__$chonk_start_swift(uint32_t num_circuits);
struct __private__OptionBool __swift_bridge__$chonk_load_swift(void* name, void* bytecode, void* verification_key);
struct __private__OptionBool __swift_bridge__$chonk_accumulate_swift(void* witness);
void* __swift_bridge__$chonk_prove_swift(void);
struct __private__OptionBool __swift_bridge__$chonk_verify_swift(void* proof, void* vk);
void* __swift_bridge__$chonk_compute_vk_swift(void* bytecode);
struct __private__OptionBool __swift_bridge__$chonk_destroy_swift(void);
void* __swift_bridge__$chonk_prove_transaction_swift(void* steps_json, bool low_memory_mode, uint64_t storage_cap);


