// File automatically generated by swift-bridge.
import SwoirenbergLib
public func setup_srs_swift<GenericToRustStr: ToRustStr>(_ circuit_size: UInt32, _ srs_path: Optional<GenericToRustStr>) -> Optional<UInt32> {
    return optionalRustStrToRustStr(srs_path, { srs_pathAsRustStr in
        __swift_bridge__$setup_srs_swift(circuit_size, srs_pathAsRustStr).intoSwiftRepr()
    })
}
public func setup_srs_from_bytecode_swift<GenericToRustStr: ToRustStr, GenericIntoRustString: IntoRustString>(_ circuit_bytecode: GenericIntoRustString, _ srs_path: Optional<GenericToRustStr>) -> Optional<UInt32> {
    return optionalRustStrToRustStr(srs_path, { srs_pathAsRustStr in
        __swift_bridge__$setup_srs_from_bytecode_swift({ let rustString = circuit_bytecode.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), srs_pathAsRustStr).intoSwiftRepr()
    })
}
public func setup_grumpkin_srs_swift<GenericToRustStr: ToRustStr>(_ num_points: UInt32, _ srs_path: Optional<GenericToRustStr>) -> Optional<UInt32> {
    return optionalRustStrToRustStr(srs_path, { srs_pathAsRustStr in
        __swift_bridge__$setup_grumpkin_srs_swift(num_points, srs_pathAsRustStr).intoSwiftRepr()
    })
}
public func setup_srs_raw_swift(_ g1_data: RustVec<UInt8>, _ num_points: UInt32) -> RustString {
    RustString(ptr: __swift_bridge__$setup_srs_raw_swift({ let val = g1_data; val.isOwned = false; return val.ptr }(), num_points))
}
public func setup_grumpkin_srs_raw_swift(_ g1_data: RustVec<UInt8>, _ num_points: UInt32) -> RustString {
    RustString(ptr: __swift_bridge__$setup_grumpkin_srs_raw_swift({ let val = g1_data; val.isOwned = false; return val.ptr }(), num_points))
}
public func prove_swift<GenericIntoRustString: IntoRustString>(_ circuit_bytecode: GenericIntoRustString, _ initial_witness: RustVec<GenericIntoRustString>, _ proof_type: GenericIntoRustString, _ vkey: RustVec<UInt8>, _ low_memory_mode: Bool, _ storage_cap: UInt64) -> Optional<RustVec<UInt8>> {
    { let val = __swift_bridge__$prove_swift({ let rustString = circuit_bytecode.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let val = initial_witness; val.isOwned = false; return val.ptr }(), { let rustString = proof_type.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let val = vkey; val.isOwned = false; return val.ptr }(), low_memory_mode, storage_cap); if val != nil { return RustVec(ptr: val!) } else { return nil } }()
}
public func verify_swift<GenericIntoRustString: IntoRustString>(_ proof: RustVec<UInt8>, _ vkey: RustVec<UInt8>, _ proof_type: GenericIntoRustString) -> Optional<Bool> {
    __swift_bridge__$verify_swift({ let val = proof; val.isOwned = false; return val.ptr }(), { let val = vkey; val.isOwned = false; return val.ptr }(), { let rustString = proof_type.intoRustString(); rustString.isOwned = false; return rustString.ptr }()).intoSwiftRepr()
}
public func execute_swift<GenericIntoRustString: IntoRustString>(_ circuit_bytecode: GenericIntoRustString, _ initial_witness: RustVec<GenericIntoRustString>) -> Optional<RustVec<RustString>> {
    { let val = __swift_bridge__$execute_swift({ let rustString = circuit_bytecode.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let val = initial_witness; val.isOwned = false; return val.ptr }()); if val != nil { return RustVec(ptr: val!) } else { return nil } }()
}
public func get_vkey_swift<GenericIntoRustString: IntoRustString>(_ circuit_bytecode: GenericIntoRustString, _ proof_type: GenericIntoRustString, _ low_memory_mode: Bool, _ storage_cap: UInt64) -> Optional<RustVec<UInt8>> {
    { let val = __swift_bridge__$get_vkey_swift({ let rustString = circuit_bytecode.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = proof_type.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), low_memory_mode, storage_cap); if val != nil { return RustVec(ptr: val!) } else { return nil } }()
}
public func chonk_start_swift(_ num_circuits: UInt32) -> Optional<Bool> {
    __swift_bridge__$chonk_start_swift(num_circuits).intoSwiftRepr()
}
public func chonk_load_swift<GenericIntoRustString: IntoRustString>(_ name: GenericIntoRustString, _ bytecode: RustVec<UInt8>, _ verification_key: RustVec<UInt8>) -> Optional<Bool> {
    __swift_bridge__$chonk_load_swift({ let rustString = name.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let val = bytecode; val.isOwned = false; return val.ptr }(), { let val = verification_key; val.isOwned = false; return val.ptr }()).intoSwiftRepr()
}
public func chonk_accumulate_swift(_ witness: RustVec<UInt8>) -> Optional<Bool> {
    __swift_bridge__$chonk_accumulate_swift({ let val = witness; val.isOwned = false; return val.ptr }()).intoSwiftRepr()
}
public func chonk_prove_swift() -> Optional<RustVec<UInt8>> {
    { let val = __swift_bridge__$chonk_prove_swift(); if val != nil { return RustVec(ptr: val!) } else { return nil } }()
}
public func chonk_verify_swift(_ proof: RustVec<UInt8>, _ vk: RustVec<UInt8>) -> Optional<Bool> {
    __swift_bridge__$chonk_verify_swift({ let val = proof; val.isOwned = false; return val.ptr }(), { let val = vk; val.isOwned = false; return val.ptr }()).intoSwiftRepr()
}
public func chonk_compute_vk_swift(_ bytecode: RustVec<UInt8>) -> Optional<RustVec<UInt8>> {
    { let val = __swift_bridge__$chonk_compute_vk_swift({ let val = bytecode; val.isOwned = false; return val.ptr }()); if val != nil { return RustVec(ptr: val!) } else { return nil } }()
}
public func chonk_destroy_swift() -> Optional<Bool> {
    __swift_bridge__$chonk_destroy_swift().intoSwiftRepr()
}
public func chonk_prove_transaction_swift<GenericIntoRustString: IntoRustString>(_ steps_json: GenericIntoRustString, _ low_memory_mode: Bool, _ storage_cap: UInt64) -> Optional<RustVec<UInt8>> {
    { let val = __swift_bridge__$chonk_prove_transaction_swift({ let rustString = steps_json.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), low_memory_mode, storage_cap); if val != nil { return RustVec(ptr: val!) } else { return nil } }()
}


