name: CelariWallet
options:
  bundleIdPrefix: com.celari
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "GBQUC68GE9"
    INFOPLIST_KEY_NSFaceIDUsageDescription: "Celari Wallet uses Face ID to secure your transactions"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"

targets:
  CelariWallet:
    type: application
    platform: iOS
    sources:
      - path: CelariWallet
        excludes:
          - "**/*.xcassets"
    resources:
      - path: CelariWallet/Assets.xcassets
      - path: CelariWallet/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.celari.wallet
        MARKETING_VERSION: "0.5.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: "Celari"
    entitlements:
      path: CelariWallet/CelariWallet.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.celari.wallet

  CelariWalletTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CelariWalletTests
    dependencies:
      - target: CelariWallet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.celari.wallet.tests
        GENERATE_INFOPLIST_FILE: true
